require 'rspec'
require_relative '../lib/set-1/1-hex-to-base64'
require_relative '../lib/set-1/2-fixed-xor'
require_relative '../lib/set-1/3-single-byte-xor'
require_relative '../lib/set-1/4-detect-single-byte-xor'
require_relative '../lib/set-1/5-implement-repeating-key-xor'
require_relative '../lib/set-1/6-break-repeating-key-xor'
require_relative '../lib/set-1/7-AES-in-ECB-mode'